<a href="https://colab.research.google.com/github/defirefly/coding/blob/main/Copy_of_Untitled14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google .colab import files
supermarket=files.upload()


Saving Supermarket_sales.csv to Supermarket_sales.csv


In [ ]:
import pandas
dataframe=pandas.read_csv("Supermarket_sales.csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [ ]:
dataframe.head(5)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   
4       Sports and travel      86.31         7  634.3785   2/8/2019  10:37   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4  
4      Ewallet  604.17                 4.761905        30.2085     5.3

In [ ]:
dataframe.tail(8)

No    InvoiceID Branch       City Customertype  Gender  \
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6900  1022.4900   
997      Food and beverages      31.84         1   1.5920    33.4320   
998      Home and lifestyle      65.82         1   3.2910    69.1110   
999     Fashion accessories      88.34         7  30.9190   649.2990   

          Date   Time  Payment    cogs  gross_margin_percentage  \
992  3/10/2019  20:46  Ewallet  116.06                 4.761905   
993  2/22/2019  18:35  Ewallet  174.90                 4.761905   
994  2/18/2019  11:40  Ewallet   60.95                 4.761905   
995  1/29/2019  13:46  Ewallet   40.35                 4.761905   
996   3/2/2019  17:16  Ewallet  973.80                 4.761905   
997   2/9/2019  13:22     Cash   31.84                 4.761905   
998  2/22/2019  15:33     Cash   65.82                 4.761905   
999  2/18/2019  13:28     Cash  618.38                 4.761905   

     gross_iincome  Rating  
992         5.8030     8.8  
993         8.7450     6.6  
994         3.0475     5.9  
995         2.0175     6.2  
996        48.6900     4.4  
997         1.5920     7.7  
998         3.2910     4.1  
999        30.9190     6.6

In [ ]:
dataframe.loc[4]

No                                         5
InvoiceID                        373-73-7910
Branch                                     A
City                                  Yangon
Customertype                          Normal
Gender                                  Male
Productline                Sports and travel
Unitprice                              86.31
Quantity                                   7
Tax                                  30.2085
Total                               634.3785
Date                                2/8/2019
Time                                   10:37
Payment                              Ewallet
cogs                                  604.17
gross_margin_percentage             4.761905
gross_iincome                        30.2085
Rating                                   5.3
Name: 4, dtype: object

In [ ]:
dataframe=dataframe.drop(['Tax'],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4

In [ ]:
print(dataframe.index)

RangeIndex(start=0, stop=1000, step=1)


In [ ]:
dataframe.Unitprice.max()

99.96

In [ ]:
dataframe.Unitprice.idxmax()

122

In [ ]:
dataframe.loc[122]

No                                       123
InvoiceID                        219-22-9386
Branch                                     B
City                                Mandalay
Customertype                          Member
Gender                                  Male
Productline                Sports and travel
Unitprice                              99.96
Quantity                                   9
Total                                944.622
Date                                3/9/2019
Time                                   17:26
Payment                          Credit card
cogs                                  899.64
gross_margin_percentage             4.761905
gross_iincome                         44.982
Rating                                   4.2
Name: 122, dtype: object

In [ ]:
dataframe.Unitprice.min()

10.08

In [ ]:
dataframe.Unitprice.idxmax()

122

In [ ]:
dataframe.loc[122]

No                                       123
InvoiceID                        219-22-9386
Branch                                     B
City                                Mandalay
Customertype                          Member
Gender                                  Male
Productline                Sports and travel
Unitprice                              99.96
Quantity                                   9
Total                                944.622
Date                                3/9/2019
Time                                   17:26
Payment                          Credit card
cogs                                  899.64
gross_margin_percentage             4.761905
gross_iincome                         44.982
Rating                                   4.2
Name: 122, dtype: object

In [ ]:
dataframe.Unitprice.mean()

55.67213

In [ ]:
import numpy as np
student_marks=[[12,14,10],[14,12,11],[15,13,12]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 14 10]
 [14 12 11]
 [15 13 12]]


In [ ]:
import numpy as np
student_marks=[[12,13],[13,14],[14,15],[15,16]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 13]
 [13 14]
 [14 15]
 [15 16]]


In [ ]:
marksarray.shape

(4, 2)

In [ ]:
values1=np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
values=np.arange(1,11)
print(values)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
values3=np.arange(70,100)
print(values3)

[70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93
 94 95 96 97 98 99]


In [ ]:
zeroarray=np.zeros(8)
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
zeroarray=np.zeros((4,2))
print(zeroarray)z

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
onesarray2=np.ones((4,2))
print(onesarray2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
len(zeroarray)

4

In [ ]:
firstarray=np.array([[10,20,30,40],[2,4,6,8],[5,10,15,20]])
print(firstarray.shape)

(3, 4)


In [ ]:
secondarray=firstarray.reshape(4,3)
print(secondarray)

[[10 20 30]
 [40  2  4]
 [ 6  8  5]
 [10 15 20]]
